name: consume
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  share: ^0.6.0+1
  shared_preferences: ^0.4.3
  date_format: ^1.0.6
  flutter_orion_icons:
    version: ^0.0.55
    git: git@bitbucket.org:quantum-labs/flutter-orion-icons.git
  quantumlabs_flutter_widgets:
    version: ^1.1.1
    git: git@bitbucket.org:quantum-labs/quantumlabs-flutter-widgets.git

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/Twitter.png
    - assets/Gustavo.jpeg

  uses-material-design: true
